### ISSUE TITLE
Get meeting date format nicer (fix type via GraphQL)

### ISSUE THREAD

**Issue by micleners** [dsmjs/site#459]
**Issue:** The date that is being formatted for the meeting is coming across in this format:
`2018-06-19T00:00:00.000Z`

**End Goal:** Use graphQL date formatter as [seen here](https://github.com/dsmjs/site/blob/master/src/pages/index.js#L38)

**Further Details:**
This is caused by `gatsby-transformer-remark` parsing the markdown frontmatter `date` value as a `string`.

It has been diagnosed that if you remove the `talk` markdown files, the date parses fine, as seen [in this PR](https://github.com/dsmjs/site/pull/458).

~~Eventually these talk markdown files will be removed, but until they are we would like to fix this issue, and keep the files as they are for historical reasons.~~ These markdown files are used to pull in `talk` information into the meetings. One solution is to convert the dates need to `YYYY-MM-DD` format as described below

**Comment by travi** [comment]
> Eventually these talk markdown files will be removed, but until they are we would like to fix this issue, and keep the files as they are for historical reasons.

as discussed separately, its worth being aware that this part isnt the plan. the front matter of the talks are used to populate parts of the data on the page as well as establish relationships with meetings, etc

> It has been diagnosed that if you remove the talk markdown files

rather than removing the files, it should be enough to ensure that the dates in the front matter of the talks (and maybe other files) adhere to the `YYYY-MM-DD` format. could you confirm that as accurate @micleners?

**Comment by micleners** [comment]
Thanks for clearing this up.

Yes, I can confirm that changing the date data in all talks to `YYYY-MM-DD` will get graphQL to recognize the date field as `Date` and not `string`.

**Comment by micleners** [comment]
Apparently an easy fix is to just change `date` to something else in all the talk files. Is there any reason to keep the `date` field with this exact name? I feel like the `date` value doesn't really belong here anyhow, since it's redundant from the `meeting` markdown..

**Comment by travi** [comment]
i'm confused. i know its been a while since i gave this a close look, but isnt date a foreign key in relating the talk with a meeting?

**Comment by travi** [comment]
it looks like the title is actually the foreign key. i think you've been trying to tell me this, but i wasnt understanding because i was assuming incorrectly that the date still defined the relationship (it used to on the old site).

i think it should be safe to just remove the date completely from the talk files

**Comment by travi** [comment]
we should probably still confirm that the format of the date in the meeting files aligns with the `YYYY-MM-DD` format, though

**Comment by micleners** [comment]
Yes, as far as I can tell the title is the foreign key for the meetings

> i think it should be safe to just remove the date completely from the talk files

Leaving the `date` in the talk might be a good idea until we convert them all to meetings. Once they are all associated with meetings, then the information can be stripped. Also, as far as fixing this issue is concerned - it's not necessary to strip the dates from the talks.

> we should probably still confirm that the format of the date in the meeting files aligns with the `YYYY-MM-DD` format, though

How should we do this? There are only two meeting files and they both adhere to this.

**Comment by travi** [comment]
> Once they are all associated with meetings, then the information can be stripped.

fair point. maybe worth cleaning up after the rest of the data is migrated
